rules:
  header-case:
  - 2
  - always
  - - sentence-case
  header-max-length:
  - 2
  - always
  - 50
  header-full-stop:
  - 2
  - never
  - "."
  body-case:
  - 2
  - always
  - - sentence-case
  body-leading-blank:
  - 2
  - always
  type-empty:
  - 2
  - always
