name: Check changelog

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      release_type:
        description: The release type extracted from changelog
        value: ${{ jobs.check_changelog.outputs.release_type }}

jobs:
  check_changelog:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'No Release') }}
    runs-on: [ ubuntu-latest ]
    outputs:
      release_type: ${{ steps.set_release_type_output.outputs.release_type }}
    steps:
      - uses: actions/checkout@v4

      - name: Validate changelog
        run: npm run changelog --silent -- --validate

      - name: Get release type in changelog
        run: echo "RELEASE_TYPE=$(npm run changelog --silent -- --get-release-type)" >> $GITHUB_ENV

      - name: Make release type available to subsequent jobs # For backwards compatibility, as this workflow is used in other Open Terms Archive repositories
        if: env.RELEASE_TYPE
        id: set_release_type_output
        run: |
          echo "Found release type '${{ env.RELEASE_TYPE }}'"
          echo "release_type=${{ env.RELEASE_TYPE }}" >> $GITHUB_OUTPUT
