name: Changelog

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      release_type:
        description: The release type extracted from changelog
        value: ${{ jobs.validate_changelog.outputs.release_type }}
      no_functional_changes:
        description: A boolean signaling that there are no functional changes in the changeset
        value: ${{ jobs.check_functional_changes.outputs.no_functional_changes }}

jobs:
  check_functional_changes:
    runs-on: ubuntu-latest
    outputs:
      no_functional_changes: ${{ steps.set_no_functional_changes.outputs.no_functional_changes }}
    steps:
      - name: Use common changelog action
        uses: OpenTermsArchive/manage-changelog/check-functional-changes@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  validate_changelog:
    if: ${{ needs.check_functional_changes.outputs.no_functional_changes != 'true' }}
    needs: [ check_functional_changes ]
    runs-on: ubuntu-latest
    outputs:
      release_type: ${{ steps.set_release_type_output.outputs.release_type }}
    steps:
      - name: Use validate changelog action
        uses: OpenTermsArchive/manage-changelog/validate-changelog@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  manage_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Use changelog manager
        uses: OpenTermsArchive/manage-changelog/changelog-manager@v1.0.0
        with:
          action: 'validate'
          changelogPath: 'CHANGELOG.md'
