name: Changelog

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      release_type:
        description: The release type extracted from changelog
        value: ${{ jobs.validate_changelog.outputs.release_type }}
      no_functional_changes:
        description: A boolean signaling that there are no functional changes in the changeset
        value: ${{ jobs.check_functional_changes.outputs.no_functional_changes }}

jobs:
  check_functional_changes:
    runs-on: ubuntu-latest
    outputs:
      no_functional_changes: ${{ steps.set_no_functional_changes.outputs.no_functional_changes }}
    steps:
      - name: Use changelog manager
        uses: OpenTermsArchive/manage-changelog/changelog-manager@v1
        with:
          action: 'check-functional-changes'

  validate_changelog:
    if: ${{ needs.check_functional_changes.outputs.no_functional_changes != 'true' }}
    needs: [ check_functional_changes ]
    runs-on: ubuntu-latest
    outputs:
      release_type: ${{ steps.set_release_type_output.outputs.release_type }}
    steps:
      - name: Use validate changelog action
        uses: OpenTermsArchive/manage-changelog/validate-changelog@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  manage_changelog:
    runs-on: ubuntu-latest
    outputs:
      release_type: ${{ steps.get-release-type.outputs.type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use changelog manager
        uses: OpenTermsArchive/manage-changelog/changelog-manager@v1
        id: get-release-type
        with:
          action: 'get-release-type'

      - name: Print Output
        run: echo "${{ steps.get-release-type.outputs.type }}"
