name: Release

on:
  push:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  changelog:
    uses: "./.github/workflows/changelog.yml"
  release:
    needs: [ changelog ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git author
        run: |
          git config --global user.name "Open Terms Archive Release Bot"
          git config --global user.email "release-bot@opentermsarchive.org"

      - name: Update changelog for release
        id: release-changelog
        uses: OpenTermsArchive/changelog-action/release@v0.2.0

      - name: Bump package version
        run: npm --no-git-tag-version version ${{ steps.release-changelog.outputs.version }}

      - name: Commit CHANGELOG.md and package.json changes and create tag
        run: |
          git add "package.json"
          git add "package-lock.json"
          git add "CHANGELOG.md"
          git commit -m "Release v${{ steps.release-changelog.outputs.version }}"
          git tag v${{ steps.release-changelog.outputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.release-changelog.outputs.version }}
          body: ${{ steps.release-changelog.outputs.content }}
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci
      - run: npm --version
      - run: npm publish
